# Generated by Django 4.1.3 on 2022-11-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('referredBy', models.CharField(max_length=55)),
                ('isOnline', models.BooleanField(default=False)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.agegroup')),
                ('event', models.ManyToManyField(to='category.event')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'participant',
            },
        ),
    ]
