# Generated by Django 4.0.7 on 2022-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_agegroup_event_agegroup_event'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(blank=True, to='category.event'),
        ),
    ]
