# Generated by Django 4.0.7 on 2022-11-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_alter_participant_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='age_group',
            new_name='ageGroup',
        ),
    ]
