# Generated by Django 4.0.7 on 2022-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_alter_participant_event'),
        ('category', '0002_remove_agegroup_event_agegroup_event'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('participant', 'event')},
        ),
    ]
