# Generated by Django 4.0.7 on 2022-11-19 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_performance_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
