# Generated by Django 4.1.2 on 2022-11-19 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_performance_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['duration'], 'verbose_name': 'Performance', 'verbose_name_plural': 'Performances'},
        ),
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='hh:mm:ss.ms'),
        ),
    ]
