# Generated by Django 4.1.2 on 2022-11-20 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_alter_performance_options_alter_performance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='format: hh:mm:ss.ms'),
        ),
    ]
