# Generated by Django 4.1.3 on 2022-11-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('minAge', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('maxAge', models.PositiveSmallIntegerField(blank=True, default=12, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.event')),
            ],
            options={
                'verbose_name': 'Age Group',
                'verbose_name_plural': 'Age Groups',
                'db_table': 'age_group',
            },
        ),
    ]
